### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Schoultzies** [ThomasPrior/2minersInfo#1]
Install via HACS and restart. All good, no error in logs.

Add

  - platform: 2minersInfo
    miner_address: "0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    currency_name: USD
    token: eth
    solo: false

to configuration.yaml (under sensors:)

Fails to restart with log below-

[547442883216] The system cannot restart because the configuration is not valid: Platform error sensor.2minersInfo - Integration '2minersInfo' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 189, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 679, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error sensor.2minersInfo - Integration '2minersInfo' not found.

**Comment by ThomasPrior** [comment]
Try a lower case "i" in ```platform: 2minersinfo```

**Comment by ThomasPrior** [comment]
Hey @Schoultzies, I haven't heard back from you for a while so I'll close the ticket in 24 hours unless there's anything more to add.

**Comment by Schoultzies** [comment]
My thanks and apologies. Works great- thanks.
